### ISSUE TITLE
Being able to change the position of the splits in fullscreen

### ISSUE THREAD

**Issue by skidzin** [mleise/livesplit_overlay#1]
I'm trying to use the add-on with Snes9x and i'm facing issues when it comes to place the splits in a certain part of the screen. As you can see, there is a gap in the emulator (which i would like to place my splits). Is there a way to do this?
Sorry for the bad english and thanks in advance.
![Screenshot_2](https://github.com/mleise/livesplit_overlay/assets/134545513/b3a913f2-0cde-40a3-aec3-4a9ca71fff49)

**Comment by mleise** [comment]
Hi skidzin! I simply used ReShade's overlay for this as it was the easiest way to draw an image on screen. Unfortunately it doesn't allow us to get rid of the padding.

**Comment by mleise** [comment]
Good news, I'm working on the next version that will allow you to position the overlay freely in the game window.

**Comment by mleise** [comment]
Problem solved.
